# spring.datasource.name=test
# spring.datasource.url=jdbc:mysql://localhost:3306/JWTDATA?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=true
# spring.datasource.username=root
# spring.datasource.password=Ankit@2003
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/JWTDATA
        username: root
        password: Ankit@2003
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create-drop
        database: mysql
        show-sql: true